### ISSUE TITLE
Some problems about using different picker on same page

### ISSUE THREAD

**Issue by mhkoca** [priyank-p/simplepicker#32] opened 2021-01-18 12:23 UTC
Hi. There is a problem I cannot understand.

At first I tried to create two pickers on same page:

 ```
$scope.onClickPlannedShipmentDateTime = function () {
                var simplepicker = new SimplePicker({
                    zIndex: 10
                });

                simplepicker.open();

                simplepicker.on('submit', (date, readableDate) => {
                    console.log(date);
                    $scope.transportationOrderManagementModel.PlannedShipmentDateTime = moment(date).format("DD.MM.YYYY HH.mm.ss");
                    $scope.$apply();
                simplepicker.close();
                    console.log(readableDate);
                });

                simplepicker.on('close', (date) => {
                    console.log('Picker Closed');
                });
            }

            $scope.onClickPlannedDeliveryDateTime = function () {
                var simplepickerlannedDeliveryDate = new SimplePicker( {
                    zIndex: 10
                });

                simplepickerlannedDeliveryDate.open();

                simplepickerlannedDeliveryDate.on('submit', (date, readableDate) => {
                    console.log(date);
                    $scope.transportationOrderManagementModel.PlannedDeliveryDateTime = moment(date).format("DD.MM.YYYY HH.mm.ss");
                    $scope.$apply();
                    simplepickerlannedDeliveryDate.close();
                    console.log(readableDate);
                });

                simplepickerlannedDeliveryDate.on('close', (date) => {
                    console.log('Picker Closed');
                });
            }
            
        };
```
But when I change the second picker value at the same time the first picker is set with the same value.

And then, I tried to create a picker with a selector but it is didn't open. There is no error at the console.

```
var simplepicker = new SimplePicker(".plannedShipmentDateTime");
....
var simplepickerlannedDeliveryDate= new SimplePicker(".plannedDeliveryDateTime");
```

I think that it may be about z-index and than I tried like that but it didn't open:

```
var simplepicker = new SimplePicker(".plannedShipmentDateTime", {
                    zIndex: 10
                });
...
var simplepickerlannedDeliveryDate = new SimplePicker(".plannedDeliveryDateTime", {
                    zIndex: 10
                });
```

Can you help me?

**Comment by mhkoca** [comment] 2021-01-18 15:44
actually, the 'open' function adds 'active' class to 'simplepicker-wrapper' element but the modal doesn't open.

**Comment by priyank-p** [comment] 2021-01-21 14:48
Quick question: Are you using the latest version? We fixed this line of bug in the last update or so.

**Comment by priyank-p** [comment] 2021-01-21 14:53
I checked [on this page] that multiple simplepicker on the same page work. That page I linked uses the current version. Of course, there still could be a bug with z-index but I am pretty sure just not using the latest version.

**Comment by priyank-p** [comment] 2021-01-21 14:55
I checked the code for the page I linked at it also uses z-index see: https://github.com/priyank-p/simplepicker/blob/f05dbde4f13c8bd8f941e8a95b70fdde2a3044f0/index-multi.html#L48-L54

**Comment by priyank-p** [comment] 2021-04-11 20:29
Closing because of the lack of reply and my inability to reproduce the problem.

**Closed by priyank-p** 2021-04-11 20:29 UTC
Labels: bug
